# Generated by Django 3.2.9 on 2022-01-18 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0004_auto_20220112_1418'),
        ('wedding', '0004_auto_20220118_1303'),
    ]

    operations = [
    ]
