# Generated by Django 3.2.9 on 2022-01-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0005_merge_0004_auto_20220112_1418_0004_auto_20220118_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalservices',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='additionalservices',
            name='caution',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='ceremonyplace',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ceremonyplace',
            name='caution',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='invitations',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='invitations',
            name='caution',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='music',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='music',
            name='caution',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='caution',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='weddinghall',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='weddinghall',
            name='caution',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
