# Generated by Django 3.2.9 on 2022-01-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0008_auto_20220119_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weddinghall',
            name='accomodation',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weddinghall',
            name='guest_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
